apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_password
  WORKSHOP_POSTGRES_USER: bookdbadmin
  WORKSHOP_POSTGRES_PASSWORD: dbpassword
